# Generated by Django 5.0.6 on 2024-06-16 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comida',
            name='images',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='images',
        ),
        migrations.AlterField(
            model_name='asignacioncomida',
            name='comida',
            field=models.ForeignKey(db_column='id_comida', on_delete=django.db.models.deletion.CASCADE, to='nutritec.comida'),
        ),
        migrations.AlterField(
            model_name='asignacioncomida',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='nutritec.usuario'),
        ),
        migrations.AlterField(
            model_name='asignacionejercicio',
            name='ejercicio',
            field=models.ForeignKey(db_column='id_ejercicio', on_delete=django.db.models.deletion.CASCADE, to='nutritec.ejercicio'),
        ),
        migrations.AlterField(
            model_name='asignacionejercicio',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='nutritec.usuario'),
        ),
        migrations.AlterField(
            model_name='comida',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria_comida', on_delete=django.db.models.deletion.CASCADE, to='nutritec.categoriacomida'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='tipo_imc',
            field=models.ForeignKey(db_column='id_tipo_imc', on_delete=django.db.models.deletion.CASCADE, to='nutritec.tipoimc'),
        ),
        migrations.AlterField(
            model_name='registroimc',
            name='tipo_imc',
            field=models.ForeignKey(db_column='id_tipo_imc', on_delete=django.db.models.deletion.CASCADE, to='nutritec.tipoimc'),
        ),
        migrations.AlterField(
            model_name='registroimc',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='nutritec.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
