# Generated by Django 5.0.6 on 2024-05-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='nutri/'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='nutri/'),
        ),
    ]
